name: Deploy to HuggingFace Space

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Push to HF
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        
        git clone https://$HF_TOKEN@huggingface.co/spaces/atulkant/Human_Sentiment_Analysis hf_space

        cp -r * hf_space/
        cd hf_space

        git add .
        git commit -m "Update space" || true
        git push
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}